apiVersion: v1
kind: ConfigMap
metadata:
  name: ocr-config
  labels:
    project: ocr
data:
  POSTGRES_DB: "postgres"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "12345"
  TOKEN: place_token_here
